### ISSUE TITLE
Initial comments

### ISSUE THREAD

**Issue by lb42** [LingSIG/wordAttributes#3]
1. @pos and @feats overlap considerably with the functionality of existing @ana : you need to explain what the differences are and why one might prefer one or the other.  I also wonder whether anyone would ever really want to use them simultaneously.
2. @reg still seems unnecessary to me : what's wrong with doing things properly ?
3. @join seems like a cool idea though, probably because we already have  something very like it on pc/@force : I'm surprised no-one is proposing a "multiword" element instead though.
4. @lemma is, as you say, already there. So why is it on this list?

**Comment by bansp** [comment]
Thanks, Lou.
1) it's fairly standard to use `@pos` and `@feats` simultaneously, unless combined information is used, usually constructed in a positional fashion, with pos coming first and followed by a list of grammatical features. Still, not a bad point for discussion, given that we should minimize the impact on the existing TEI model, to maximize the chance of getting the proposal accepted.
2) "properly" has a weasel way of meaning different things to different people; in this case `@reg` is a well-attested compromise of providing the regularized value as an attribute, without exploding the markup.
3) right, we discussed `pc/@pre` briefly (or did you really mean `@force`?), as a rather limited tool that `@join` generalizes over (in terms of both the domain and the range: it would apply to all token-level elements and would be capable of expressing more than two values)
4) oh, I believe just for the sake of completeness; maybe I failed to clearly distinguish between the complete target vision and what exactly could/should be added to the already existing repertoire -- will have a look, thanks

**Comment by lb42** [comment]
1. "Fairly standard" meaning "fairly common", I assume (considering your comments elsewhere on the use of the word "standard" :-) 
2. "well-attested" -- any evidence for that? I have lots of evidence of people happily  using &lt;choice> to handle regularisation in historical corpora btw. And why adding a gazillion attributes doesn't count as "exploding the markup" you can explain to me another day.
3. No, I really meant @force. But maybe I misunderstand what @join is for. Will check.

**Comment by bansp** [comment]
1. My comments elsewhere concerned the noun "standard" in the phrase "developing a standard" :-) But I take your point -- I have used weasel statements myself here, indeed...
2. ... which also includes the "well-attested". Maybe indeed the reductionist exercise here should yield a proposal for a single `@pos` attribute that could potentially be internally complex (and concatenate the information on the pos and on the morphosyntactic features).
3. I'm a bit lost and will study `@force` to see how it could be used.
4. Tomaz in issue #3 provides an argument against using `@reg` (which corroborates your point 2. in the initial note).

**Comment by bansp** [comment]
Thanks for your remarks, Lou -- they have improved the eventual proposal.
Closing this issue after the [merger with TEI/dev](https://github.com/TEIC/TEI/commit/b7bb4e5f8de534a3b3cd1b73501fcf57e6264ad0) .
